
spring:
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
    instance:
      preferIpAddress: true
