
server:
  port: 8080
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth_route
            uri: lb://auth.service
            predicates:
              - Path=/api/auth/**
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: true
