server:
  port: 8080
spring:
  application:
    name: auth.service
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_service
    username: postgres
    password: best_password
  kafka:
    consumer:
      group-id: auth.service

app:
  jwt:
    refresh-secret: best_secret
    refresh-duration: 2592000
  kafka:
    creator-id: auth-service
